[package]
name = "dont_disappear"
version = "0.0.6"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
Tiny crates that stops the console window form closing when the program finishes.
"""
[dependencies]